### PR TITLE
Update home page content

### PR DESCRIPTION
**Pull request by kburakozdemir**
Drupal 8 -> Drupal 9

image

image

### CODE REVIEW

**Comment by mortenson** [comment]
@kburakozdemir Did you run `drush tome:export` when working on this pull request? I see many nodes updates that are unrelated to the homepage.

**Comment by kburakozdemir** [comment]
Nope I didn't run `drush tome:export`. If I should have run it and I didn't, I can fix it via a new pull request. You can close this unmerged.

**Comment by mortenson** [comment]
@kburakozdemir All good, I just assumed you had run that command given the number of changes. It'd be nice if the PR only included changes for the homepage - not sure how the other edits got in there.

**Comment by kburakozdemir** [comment]
@mortenson no problem. I think we should close this unmerged and I will try it once again (of course again w/o `drush tome:export`) and create a new PR.

**Pull request closed without merging**
